library/config/routes.rb
Library::Application.routes.draw do
  
  resources :books do 
    get 'page/:page', :action => :index, :on => :collection
  end

  get "/reservations/overdue" => "reservations#overdue"
  post "/reservations/kill" => "reservations#destroy"
  resources :reservations

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :users

  get "/authors" => "authors#index", as: 'authors'
  get "/authors/:id" => "authors#show", as: 'author'

end

library/app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

library/app/views/layouts/_header.html.erb
<header class="page-header">

<h1 class="text-center text-muted"><%= link_to('Ultimate Library', sessions_new_path) %></h1>
</header>

library/app/views/layouts/_sidebar.html.erb
<div id="sidebar">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Things to do ...</h3>
  </div>
  <div class="panel-body">
    <% if session[:user_id] %>
      <p><i class="glyphicon glyphicon-book"></i>
        <%= link_to 'All Books', books_path %>
      </p>

      <p><i class="glyphicon glyphicon-user"></i>
        <%= link_to 'Authors', authors_path %>
      </p>

      <% if session[:admin] == true %> 
        <p><i class="glyphicon glyphicon-plus-sign"></i>
          <%= link_to 'New Book', new_book_path %>
        </p>

        <p><i class="glyphicon glyphicon-exclamation-sign"></i>
          <%= link_to 'Overdue Books', reservations_overdue_path %>
        </p>
      <% end %>

      <p><i class="glyphicon glyphicon-check"></i>
        <%= link_to 'My Reservations', reservations_path %>
      </p>
      
      <%= button_to 'Logout', logout_path, method: :delete %>
    <% end %> 
  </div>
</div>
</div>

library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Ultimate Library <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>