library/config/routes.rb
Library::Application.routes.draw do
  
  resources :books do 
    get 'page/:page', :action => :index, :on => :collection
  end

  get "/reservations/overdue" => "reservations#overdue"
  post "/reservations/kill" => "reservations#destroy"
  resources :reservations

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :users

  get "/authors" => "authors#index", as: 'authors'
  get "/authors/:id" => "authors#show", as: 'author'

end

library/app/models/reservation.rb
class Reservation < ActiveRecord::Base
#  belongs_to :user, dependent: :destroy
  belongs_to :book, dependent: :destroy
  belongs_to :user
  belongs_to :book
end

library/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

#before_action :set_user, only: [:index, :overdue]
before_action :set_user, only: [:index]

before_action :set_book, only: [:create]

  def index
    @reservations = @user.reservations.order('created_at desc')
  end


  # GET /reservations/overdue
  def overdue
   @overdueset = Reservation.where( "due_on < ?", Time.zone.now  )
  end

  def show
   @overdueset = Reservation.where( "due_on < ?", Time.zone.now ).order(:user_id)
  end


  def destroy
      resindex = params[ :thereservationid ] 
      resindex.inspect
      reservationobj  = Reservation.find( params[ :thereservationid] )
      reservationobj.inspect
      Reservation.find( params[ :thereservationid]  ).delete
      redirect_to books_url
  end


  def create
    user_index = params[:user_index]
    book_id = params[:book_id]
#    today = Date.today
    today = Time.zone.now
    tomorrow = today +1.days

    @reservation = @book.reservations.new( book_id: book_id, 
                                           user_id: user_index,
                                           reserved_on: today,
                                           due_on: tomorrow )

    if @reservation.save
       redirect_to reservations_path(@user), notice: 'Reservation generated!'
    else
       redirect_to books_index_path(@user), notice: 'Reservation failed!'
    end
  end

private

  def set_user
    @user = User.find(session[ :user_index ] )
  end

  def set_book
        @book = Book.find(params[:book_id])
  end

end

library/app/helpers/reservations_helper.rb
module ReservationsHelper
end

library/app/views/reservations/destroy.html.erb
<h2>Destroy Reservation </h2>

<p> the params hash is </p>
<%=  params.inspect  %>
</b>

<%= params[:thereservationid] %>
</b>

<%= Reservation.find( params[:thereservationid] ).inspect %>
</b>

library/app/views/reservations/index.html.erb
<h2>My Reservations</h2>

<ol id="reservations">
  <% @reservations.each do |reservation| %>
    <li>
      <span>
	<%= hidden_field_tag reservation.user_id %>
      </span>

      <span>
	<%= hidden_field_tag reservation.book_id %>
      </span>

      <span>
	<%= image_tag(reservation.book.image_cover_url, height: "100", width: "80")%>
      </span><br><br>

      <span class='book-title'>
	<%= reservation.book.title %>
      </span><br>

      <span class="date">
          Reserved - <%= reservation.reserved_on.to_s(:short) %> 
      </span><br>

      <span class="date">
         Due - <%= reservation.due_on.to_s(:short) %>
      </span><br>

      <span>
        <%= button_to 'Return book', reservations_kill_path(thereservationid: reservation.id , theuserid: reservation.user_id), 
                 data: {confirm: 'Are you sure?' } %>
      </span><br>


     
    </li>
  <% end %>
</ol>

library/app/views/reservations/overdue.html.erb
<h2>Overdue Book</h2>

<ol id="reservations">
  <% @overdueset.each do |reservation| %>
    <li>
      <span>
  <%= image_tag(reservation.book.image_cover_url, height: "100", width: "80") %>
      </span><br><br>

      <span>
	<%= hidden_field_tag reservation.user_id %>
      </span>

      <span>
	<%= hidden_field_tag reservation.book_id %>
      </span>

      <span class="book-title">
	<%= Book.find(reservation.book_id).title %>
      </span><br>

      <span>
	Reserved by - <%= User.find(reservation.user_id).name %>
      </span><br>

      <span class="date">
          Reserved on - <%= reservation.reserved_on.to_s(:short) %> 
      </span><br>

      <span class="date">
         Due on - <%= reservation.due_on.to_s(:short) %>
      </span><br><br>

      <span>
        <%= button_to 'Return book', reservations_kill_path(thereservationid: reservation.id, theuserid: reservation.user_id ), 
                 data: {confirm: 'Are you sure?' } %>
      </span>


     </br>
    </li>
  <% end %>
</ol>

library/app/views/reservations/show.html.erb
<h2>Overdue Reservations - via show</h2>


<ol id="reservations">
  <% @overdueset.each do |reservation| %>
    <l1>
      <span>
	<%= reservation.user_id %>
      </span>

      <span>
	<%= reservation.book_id %>
      </span>

      <span>
	| title - <%= Book.find(reservation.book_id).title %>
      </span>

      <span>
	| reserved by - <%= User.find(reservation.user_id).name %>
      </span>

      <span class="date">
          | reserved on - <%= reservation.reserved_on.to_s(:short) %> 
      </span>

      <span class="date">
         | due on - <%= reservation.due_on.to_s(:short) %>
      </span>

      <span>
        | <%= button_to 'Return book', reservations_kill_path(thereservationid: reservation.id, theuserid: reservation.user_id ), 
                 data: {confirm: 'Are you sure?' } %>
      </span>


     </br>
    </li>
  <% end %>
</ol>