library/config/routes.rb
Library::Application.routes.draw do
  
  resources :books do 
    get 'page/:page', :action => :index, :on => :collection
  end

  get "/reservations/overdue" => "reservations#overdue"
  post "/reservations/kill" => "reservations#destroy"
  resources :reservations

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :users

  get "/authors" => "authors#index", as: 'authors'
  get "/authors/:id" => "authors#show", as: 'author'

end

library/app/models/book.rb
class Book < ActiveRecord::Base
   
  def self.search(search)  
    if search  
      where(['title LIKE ? OR author LIKE ? OR isbn LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"]) 
    else  
      scoped  
    end  
  end  
  
GENRE = [ 'Sci-fi', 'Drama', 'Fiction' , 'Non-Fiction' , 'Fantasy' ]

  validates :title, :author, :isbn, :genre, :abstract, :pages,  presence: true
  
  validates :pages,
    numericality: { only_integer: true, greater_than_or_equal_to: 0 },
      unless: "pages.blank?"
  
  validates :total_in_library,
      numericality: { greater_than: 0 }

  validates :genre, :inclusion => { :in => GENRE }

  validates :abstract, length: { minimum: 15 }, 
    unless: 'abstract.blank?'

#has_many :users, through: :reservations, dependent: :destroy
has_many :users, through: :reservations

has_many :reservations

end

library/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  
  def index
    @books = Book.search(params[:search]).order(:title).page(params[:page])
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @records=Reservation.where("book_id=?" , @book.id).all
    if @records.nil?
      @recordcount = 0
    else
      @recordcount=@records.count
    end

    @myuserid = session[:user_index]

    @myreservationsforthisbook=Reservation.where("book_id=? and user_id=?", @book.id, session[:user_index]).all
#    @myreservationsforthisbook=Reservation.where("user_id=?", session[:user_index]).all
    if @myreservationsforthisbook.nil?
      @myreservationcount = 0
    else
      @myreservationcount = @myreservationsforthisbook.count
    end
  end

# GET /books/new
  def new
    @book = Book.new
    @authors = Author.all
  end

  # GET /books/1/edit
  def edit
    @authors = Author.all
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.author_id = -1
    if @book.author.to_i 
      @authors = Author.all
      @authors.each do |a|
        if @book.author.to_i == a.id
          @book.author = a.name
          @book.author_id = a.id
        end
      end
    end
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book.update(book_params)
    @book.author_id = -1
    if @book.author.to_i 
      @authors = Author.all
      @authors.each do |a|
        if @book.author.to_i == a.id
          @book.author = a.name
          @book.author_id = a.id
        end
      end
    end
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    @destroybookid=@book.id
#	delete the associated reservations
    Reservation.where( "book_id ='#{@destroybookid}'").each do |deleteit|
        deleteit.delete
    end
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn, :title, :author, :genre, :abstract, :pages, :image_cover_url, :published_on, :total_in_library)
    end
end

library/app/helpers/books_helper.rb
module BooksHelper
end

library/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
<h5> Use "Author" text field below to enter new author name</h5>
<h5>    or "Dbauthor" pull down to select name of known author </h5>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :dbauthor %><br>
    <%= f.select :author, @authors.collect { |a| [a.name, a.id ] }, {prompt: "Choose One"} %>

  </div>

  <div class="field">
    <%= f.label :genre %><br>
    <%= f.select :genre, Book::GENRE, {prompt: "Choose One"} %> 
  </div>
  <div class="field">
    <%= f.label :abstract %><br>
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.number_field :pages %>
  </div>
  <div class="field">
    <%= f.label :image_cover_url %><br>
    <%= f.text_field :image_cover_url %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br>
    <%= f.date_select :published_on %>
  </div>
  <div class="field">
    <%= f.label :total_in_library %><br>
    <%= f.number_field :total_in_library %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

library/app/views/books/edit.html.erb
<h2>Editing book</h2>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to '< Back', books_path %>

library/app/views/books/index.html.erb
<span class="search-span">
     <%= form_tag books_path, :method => 'get' do %> 
       <%= text_field_tag :search, params[:search]%>
       <%= submit_tag "Search", :book => nil  %>
     <% end %> 
</span>

<h2>Books</h2>
<span id="searchResultsTitle" style="display: none;">
<strong>Search Results</strong></span> <br>
  <p>
  <%= page_entries_info @books %> 
  </p>
  <ol>
    <% @books.each do |book| %>

    <li>
      <div class="book-content-area">
        <div class="book-image-area"><%= image_tag(book.image_cover_url, height: "100", width: "80") %>
        </div>
        <div class="title-author-area">
        <span class="book-title"><%= link_to(book.title, book) %></span><br>
        <span class="by-author"> by <%= book.author %></span>
        </div>
      </div>
    </li>
    <br>
    
  <% end %>
  <%= paginate @books %>
  </ol>
  <script type="text/javascript" language="javascript">
    showSearchHeader();
  </script>

library/app/views/books/new.html.erb
<h2>New book</h2>

<%= render 'form' %>

<%= link_to '< Back', books_path %>

library/app/views/books/show.html.erb
<p class='book-title'>
  <%= @book.title %>
</p>
<% if @book.image_cover_url.length > 0 %>
  <div class='abstract-area'>
  <div class='cover-image'>
  <%= image_tag(@book.image_cover_url, height: "100", width: "80")%>
  </div>
<% else %>
  <div class='abstract-area'>
  <p>
    <strong> no image available </strong>
  </p>
<% end %>

<div class='book-abstract'>
  <%= @book.abstract %>
</div>
</div>

<h4>Details</h4>

<p>
  <strong>ISBN:</strong>
  <%= @book.isbn %>
</p>


<p>
  <strong>Author:</strong>
  <% if @book.author_id < 1 %>
    <%= @book.author %>
  <% else %>
   <%= link_to @book.author, author_path(@book.author_id) %>
  <% end %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>


<p>
  <strong>Pages:</strong>
  <%= @book.pages %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @book.published_on %>
</p>

<p>
  <strong>Total in library:</strong>
  <%= @book.total_in_library %>
</p>

<p>
  <strong>Current copies on Reserve:</strong>
  <%= @recordcount %>
</p>

<p>
  <% if @book.total_in_library > @recordcount %>
    <strong>Copies of this book can be reserved</strong>
  <% else %>
    <strong>There are no copies of the book available to be reserved</strong>
 <% end %>
</p>

<p>

  <% if @myreservationcount > 0 %>
    <strong> You already have this book reserved</strong>
  <% else %>
    <% if @book.total_in_library > @recordcount %>
      <%= button_to 'Reserve', reservations_path(book_id: @book, user_index: session[:user_index] ) %>
    <% end %> 
  <% end %>
</p>

 <% if session[:admin] == true %> 
   <%= link_to 'Edit', edit_book_path(@book) %> |
   <%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>

<%= link_to 'Back', books_path %>